// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DemoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void demo() {
    driver.get("https://saucelabs.com/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    js.executeScript("window.scrollTo(0,0)");
    {
      WebElement element = driver.findElement(By.cssSelector(".css-2mjmhh"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".css-26bamu")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".css-107rrsf"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".css-26bamu"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiStack-root:nth-child(1) > .dropdown:nth-child(2) .MuiBox-root:nth-child(2) > .MuiStack-root:nth-child(1) .MuiBox-root:nth-child(1) > a:nth-child(1) .MuiTypography-root:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    js.executeScript("window.scrollTo(0,234)");
    driver.findElement(By.cssSelector(".MuiButton-outlinedWhite")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".Header_logo__V9h3K > img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.close();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".css-3a2c0r:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".css-30krpw:nth-child(7)")).click();
    js.executeScript("window.scrollTo(0,2200)");
    js.executeScript("window.scrollTo(0,2900)");
    js.executeScript("window.scrollTo(0,3461)");
    js.executeScript("window.scrollTo(0,4500)");
    js.executeScript("window.scrollTo(0,4800)");
    driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(6) .MuiBox-root:nth-child(8) .MuiTypography-root")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.id("Email")).click();
    driver.findElement(By.id("Email")).sendKeys("test@234gmail.com");
    driver.findElement(By.id("FirstName")).click();
    driver.findElement(By.id("FirstName")).sendKeys("Test");
    driver.findElement(By.id("LastName")).click();
    driver.findElement(By.id("LastName")).sendKeys("Demo");
    driver.findElement(By.cssSelector(".mktoFormRow:nth-child(5) span")).click();
    driver.findElement(By.id("Company")).click();
    driver.findElement(By.id("Company")).sendKeys("Tops");
    driver.findElement(By.id("Phone")).click();
    driver.findElement(By.id("Phone")).sendKeys("9909904499");
    driver.findElement(By.id("Country")).click();
    {
      WebElement dropdown = driver.findElement(By.id("Country"));
      dropdown.findElement(By.xpath("//option[. = 'India']")).click();
    }
    driver.findElement(By.id("Solution_Interest__c")).click();
    driver.findElement(By.id("Solution_Interest__c")).click();
    driver.findElement(By.id("Solution_Interest__c")).click();
    {
      WebElement dropdown = driver.findElement(By.id("Solution_Interest__c"));
      dropdown.findElement(By.xpath("//option[. = 'Visual Testing']")).click();
    }
    driver.findElement(By.id("Sales_Contact_Comments__c")).click();
    driver.findElement(By.id("Sales_Contact_Comments__c")).sendKeys("Best site For Test");
    driver.findElement(By.cssSelector(".mktoButton")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mktoButton"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
